'use client';
import {useEffect,useRef,useState} from 'react';
import {createClient} from 'genlayer-js';import {studionet} from 'genlayer-js/chains';import {TransactionStatus} from 'genlayer-js/types';

const STUDIONET_ID='0xf22f';
const STUDIONET_PARAMS={chainId:STUDIONET_ID,chainName:'GenLayer Studio Network',rpcUrls:['https://studio.genlayer.com/api'],nativeCurrency:{name:'GEN Token',symbol:'GEN',decimals:18}};

export function useLedger(address:string){const [account,setAccount]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [hash,setHash]=useState('');const reader=createClient({chain:studionet});const writer=useRef<any>(null);useEffect(()=>{const e=(window as any).ethereum;const reset=()=>{writer.current=null;setAccount('');setMessage('Wallet changed. Reconnect to continue safely.')};e?.on?.('accountsChanged',reset);e?.on?.('chainChanged',reset);return()=>{e?.removeListener?.('accountsChanged',reset);e?.removeListener?.('chainChanged',reset)}},[]);
function walletProvider(e:any){return{request:async(args:any)=>{if(args.method==='wallet_getSnaps')return{};if(args.method==='wallet_requestSnaps')return{};return e.request(args)}}}
async function ensureStudionet(e:any){const chainId=await e.request({method:'eth_chainId'});if(chainId?.toLowerCase()===STUDIONET_ID)return;try{await e.request({method:'wallet_switchEthereumChain',params:[{chainId:STUDIONET_ID}]})}catch(err:any){if(err?.code!==4902)throw err;await e.request({method:'wallet_addEthereumChain',params:[STUDIONET_PARAMS]});await e.request({method:'wallet_switchEthereumChain',params:[{chainId:STUDIONET_ID}]})}}
async function connect(){try{const e=(window as any).ethereum;if(!e)throw Error('Install an EIP-1193 wallet to continue.');const[a]=await e.request({method:'eth_requestAccounts'});await ensureStudionet(e);writer.current=createClient({chain:studionet,account:a as any,provider:walletProvider(e)});setAccount(a);setMessage('Studionet wallet connected.')}catch(x:any){setMessage(x.message)}}
async function read(method:string,args:any[]){return JSON.parse(String(await reader.readContract({address:address as any,functionName:method,args})))}
async function write(method:string,args:any[],verify:()=>Promise<boolean>){if(busy)return;setBusy(true);setHash('');setMessage('Waiting for wallet approval…');try{if(!account||!writer.current)throw Error('Connect your wallet first.');const e=(window as any).ethereum;const ac=await e.request({method:'eth_accounts'});if(ac[0]?.toLowerCase()!==account.toLowerCase())throw Error('Wallet changed. Reconnect.');await ensureStudionet(e);const h=await writer.current.writeContract({address:address as any,functionName:method,args,value:0n});setHash(h);setMessage('Submitted. Validators are fetching both sources and reaching consensus…');await reader.waitForTransactionReceipt({hash:h,status:TransactionStatus.FINALIZED,retries:180,interval:2500});const tx:any=await reader.getTransaction({hash:h});const rs=tx.consensus_data?.leader_receipt;const ex=Array.isArray(rs)?rs.find((r:any)=>r.mode==='leader')||rs[0]:rs;if(tx.result_name!=='MAJORITY_AGREE'||ex?.execution_result!=='SUCCESS')throw Error('Consensus or execution failed: '+(tx.result_name||'unconfirmed'));if(!(await verify()))throw Error('Finalized, but expected state was not found.');setMessage('Confirmed: release read back from the contract.')}catch(x:any){setMessage('Error: '+x.message)}finally{setBusy(false)}}return{account,busy,message,hash,connect,read,write}}

